#!/bin/sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=ON_ERROR_STOP=1 <<-EOSQL
CREATE ROLE $UZLLM_RUNTIME_DB_USER LOGIN PASSWORD '$UZLLM_RUNTIME_DB_PASSWORD';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $UZLLM_RUNTIME_DB_USER;
EOSQL
