using UZLLM.Observability;
using UZLLM.Persistence;
using UZLLM.Modules.ApiKeys.Infrastructure;
using UZLLM.Modules.Catalog.Infrastructure;
using UZLLM.Modules.Billing.Infrastructure;
using UZLLM.Modules.Usage.Infrastructure;
using UZLLM.Modules.Providers.Infrastructure;
using UZLLM.Provider.OpenAI;
using UZLLM.Gateway.Api.Inference;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOpenApi();
builder.Services.AddUzllmPersistence(builder.Configuration);
builder.Services.AddUzllmRedis(builder.Configuration);
builder.Services.AddUzllmObservability(builder.Configuration, "UZLLM.Gateway.Api");
builder.Services.AddUzllmReadinessChecks();
builder.Services.AddUzllmGatewayApiKeys(builder.Configuration);
builder.Services.AddUzllmCatalog();
builder.Services.AddUzllmUsage();
builder.Services.AddUzllmBilling();
builder.Services.AddUzllmProviders(builder.Configuration);
builder.Services.AddUzllmOpenAiAdapter(builder.Configuration);
builder.Services.AddSingleton(GatewayOptions.FromConfiguration(builder.Configuration));
builder.Services.AddScoped<IGatewayReadStore, PostgreSqlGatewayReadStore>();
builder.Services.AddScoped<IInferenceGateway, InferenceGateway>();
builder.Services.AddScoped<IProviderAdapterSelector, ProviderAdapterSelector>();
builder.Services.AddSingleton<ICompletionWriterFactory, OpenAiCompletionWriterFactory>();
var app = builder.Build();

app.UseUzllmRequestCorrelation();
app.MapUzllmHealthEndpoints();
app.MapUzllmInferenceEndpoints();
if (app.Environment.IsDevelopment()) app.MapOpenApi();
app.Run();
