// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UZLLM.Persistence;

#nullable disable

namespace UZLLM.Persistence.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    [Migration("20260924160524_AddCatalogFoundation")]
    partial class AddCatalogFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UZLLM.Persistence.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorAccountId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .IsDescending(false, true);

                    b.ToTable("audit_event", "audit");
                });

            modelBuilder.Entity("UZLLM.Persistence.BillingFeePolicyVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<long>("FixedFeeMicroUsd")
                        .HasColumnType("bigint")
                        .HasColumnName("fixed_fee_micro_usd");

                    b.Property<int>("MarkupBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("markup_basis_points");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("policy_code");

                    b.HasKey("Id");

                    b.HasIndex("PolicyCode", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("fee_policy_version", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_fee_policy_version_range", "effective_to IS NULL OR effective_to > effective_from");

                            t.HasCheckConstraint("CK_fee_policy_version_values", "markup_basis_points BETWEEN 0 AND 100000 AND fixed_fee_micro_usd >= 0");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.BillingFxRateSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<decimal>("UzsTiyinPerUsd")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("uzs_tiyin_per_usd");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ObservedAt");

                    b.ToTable("fx_rate_snapshot", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_fx_rate_snapshot_positive", "uzs_tiyin_per_usd > 0");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.BillingLedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMicroUsd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_micro_usd");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("OrganizationId", "Type", "ReferenceType", "ReferenceId")
                        .IsUnique();

                    b.ToTable("ledger_entry", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_ledger_entry_direction", "(amount_micro_usd > 0 AND type IN ('TopUp', 'Refund', 'AdjustmentCredit', 'PromotionalCredit')) OR (amount_micro_usd < 0 AND type IN ('UsageCharge', 'AdjustmentDebit'))");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.BillingWalletEntity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("PostedBalanceMicroUsd")
                        .HasColumnType("bigint")
                        .HasColumnName("posted_balance_micro_usd");

                    b.Property<long>("ReservedBalanceMicroUsd")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_balance_micro_usd");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationId");

                    b.ToTable("wallet", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_wallet_non_negative", "posted_balance_micro_usd >= reserved_balance_micro_usd AND reserved_balance_micro_usd >= 0");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_code");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities_json");

                    b.Property<int>("ContextLength")
                        .HasColumnType("integer")
                        .HasColumnName("context_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_output_tokens");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalCode")
                        .IsUnique();

                    b.ToTable("model", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_model_limits", "context_length > 0 AND max_output_tokens > 0 AND max_output_tokens <= context_length");

                            t.HasCheckConstraint("CK_catalog_model_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogModelPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("CachedInputPriceMicroUsdPerMillion")
                        .HasColumnType("bigint")
                        .HasColumnName("cached_input_price_micro_usd_per_million");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("ExtraPricingJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_pricing_json");

                    b.Property<long>("InputPriceMicroUsdPerMillion")
                        .HasColumnType("bigint")
                        .HasColumnName("input_price_micro_usd_per_million");

                    b.Property<long>("OutputPriceMicroUsdPerMillion")
                        .HasColumnType("bigint")
                        .HasColumnName("output_price_micro_usd_per_million");

                    b.Property<Guid>("ProviderModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_model_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderModelId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("model_price", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_model_price_range", "effective_to IS NULL OR effective_to > effective_from");

                            t.HasCheckConstraint("CK_catalog_model_price_values", "input_price_micro_usd_per_million >= 0 AND output_price_micro_usd_per_million >= 0 AND (cached_input_price_micro_usd_per_million IS NULL OR cached_input_price_micro_usd_per_million >= 0)");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("provider", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_provider_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogProviderModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapabilityOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities_override_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndpointReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint_reference");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UpstreamModelCode")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("upstream_model_code");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProviderId", "ModelId")
                        .IsUnique();

                    b.HasIndex("ProviderId", "UpstreamModelCode")
                        .IsUnique();

                    b.ToTable("provider_model", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_provider_model_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.ConsumerInboxEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("Consumer", "EventId")
                        .IsUnique();

                    b.ToTable("consumer_inbox", "ops");
                });

            modelBuilder.Entity("UZLLM.Persistence.GatewayApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("key_prefix");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<byte[]>("SecretFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_fingerprint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("api_key", "gateway", t =>
                        {
                            t.HasCheckConstraint("CK_api_key_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentityAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user", "iam");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentityChallengeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Kind")
                        .IsUnique()
                        .HasFilter("consumed_at IS NULL");

                    b.HasIndex("Kind", "TokenHash")
                        .IsUnique();

                    b.ToTable("challenge", "iam");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentityOperatorAccessEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("MfaEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<string>("ProtectedTotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("protected_totp_secret");

                    b.HasKey("AccountId");

                    b.ToTable("operator_access", "iam");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentitySessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CsrfHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("csrf_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("MfaReauthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_reauthenticated_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ExpiresAt");

                    b.ToTable("session", "iam");
                });

            modelBuilder.Entity("UZLLM.Persistence.LeasedJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("JobType", "DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("CompletedAt", "AvailableAt", "LeaseExpiresAt");

                    b.ToTable("job", "ops");
                });

            modelBuilder.Entity("UZLLM.Persistence.OperationalAlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "OccurredAt");

                    b.ToTable("operational_alert", "ops");
                });

            modelBuilder.Entity("UZLLM.Persistence.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("organization", "org");
                });

            modelBuilder.Entity("UZLLM.Persistence.OrganizationMemberEntity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("OrganizationId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("member", "org");
                });

            modelBuilder.Entity("UZLLM.Persistence.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "AvailableAt", "LeaseExpiresAt");

                    b.ToTable("outbox", "ops");
                });

            modelBuilder.Entity("UZLLM.Persistence.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Id")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("project", "gateway");
                });

            modelBuilder.Entity("UZLLM.Persistence.AuditEventEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.IdentityAccountEntity", "ActorAccount")
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UZLLM.Persistence.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorAccount");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UZLLM.Persistence.BillingLedgerEntryEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UZLLM.Persistence.BillingWalletEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogModelPriceEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.CatalogProviderModelEntity", "ProviderModel")
                        .WithMany("Prices")
                        .HasForeignKey("ProviderModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProviderModel");
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogProviderModelEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.CatalogModelEntity", "Model")
                        .WithMany("ProviderModels")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UZLLM.Persistence.CatalogProviderEntity", "Provider")
                        .WithMany("ProviderModels")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UZLLM.Persistence.GatewayApiKeyEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.IdentityAccountEntity", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UZLLM.Persistence.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentityChallengeEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.IdentityAccountEntity", "Account")
                        .WithMany("Challenges")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentityOperatorAccessEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.IdentityAccountEntity", "Account")
                        .WithOne("OperatorAccess")
                        .HasForeignKey("UZLLM.Persistence.IdentityOperatorAccessEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentitySessionEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.IdentityAccountEntity", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UZLLM.Persistence.OrganizationMemberEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.IdentityAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UZLLM.Persistence.OrganizationEntity", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UZLLM.Persistence.ProjectEntity", b =>
                {
                    b.HasOne("UZLLM.Persistence.OrganizationEntity", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogModelEntity", b =>
                {
                    b.Navigation("ProviderModels");
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogProviderEntity", b =>
                {
                    b.Navigation("ProviderModels");
                });

            modelBuilder.Entity("UZLLM.Persistence.CatalogProviderModelEntity", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("UZLLM.Persistence.IdentityAccountEntity", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("OperatorAccess");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("UZLLM.Persistence.OrganizationEntity", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
