using UZLLM.Observability;
using UZLLM.Persistence;
using UZLLM.Modules.Identity.Infrastructure;
using UZLLM.Modules.Audit.Infrastructure;
using UZLLM.Modules.ApiKeys.Infrastructure;
using UZLLM.Modules.Billing.Infrastructure;
using UZLLM.Modules.Catalog.Infrastructure;
using UZLLM.Modules.Organizations.Infrastructure;
using UZLLM.Modules.Projects.Infrastructure;
using UZLLM.Modules.Payments.Infrastructure;
using UZLLM.Modules.Usage.Infrastructure;
using UZLLM.Modules.Providers.Infrastructure;
using UZLLM.Modules.Notifications.Infrastructure;
using UZLLM.Management.Api;
using UZLLM.Management.Api.Administration;
using UZLLM.Management.Api.Budgets;

var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddKeyPerFile("/run/secrets", optional: true);
builder.Services.AddUzllmOperatorKeyRing(builder.Configuration, builder.Environment.IsProduction());
builder.Services.AddUzllmPersistence(builder.Configuration);
builder.Services.AddUzllmRedis(builder.Configuration);
builder.Services.AddUzllmObservability(builder.Configuration, "UZLLM.Management.Api");
builder.Services.AddUzllmReadinessChecks();
builder.Services.AddUzllmIdentity();
builder.Services.AddUzllmAudit();
builder.Services.AddUzllmApiKeys(builder.Configuration);
builder.Services.AddUzllmBilling();
builder.Services.AddUzllmUsage();
builder.Services.AddUzllmCatalog();
builder.Services.AddUzllmProviders(builder.Configuration);
builder.Services.AddUzllmOrganizations();
builder.Services.AddUzllmTeam();
builder.Services.AddUzllmProjects();
builder.Services.AddUzllmPayments(builder.Configuration);
builder.Services.AddUzllmCustomerAlerts(builder.Configuration);
builder.Services.AddUzllmAdministration();
builder.Services.AddScoped<IBudgetManagementService, BudgetManagementService>();
var app = builder.Build();

app.UseUzllmRequestCorrelation();
app.UseUzllmManagementSession();
app.MapUzllmHealthEndpoints();
app.MapUzllmIdentityEndpoints();
app.MapUzllmOrganizationEndpoints();
app.MapUzllmTeamEndpoints();
app.MapUzllmProjectEndpoints();
app.MapUzllmApiKeyEndpoints();
app.MapUzllmPaymentEndpoints();
app.MapUzllmUsageReadEndpoints();
app.MapUzllmPayloadRetentionEndpoints();
app.MapUzllmAdminEndpoints();
app.MapUzllmBudgetEndpoints();
app.MapUzllmByokEndpoints();
app.MapUzllmCustomerAlertEndpoints();
app.Run();
